# Generated by Django 2.2 on 2022-04-11 20:32

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True)),
                ('code_phone', models.IntegerField(max_length=3)),
                ('tag', models.CharField(max_length=20)),
                ('UTC', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MailingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start_mailing', models.DateTimeField()),
                ('code_phone', models.IntegerField()),
                ('tag', models.CharField(max_length=20)),
                ('filter_code_phone', models.CharField(max_length=20)),
                ('time_finish_mailing', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_creation', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClientModel')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MailingModel')),
            ],
        ),
    ]
